CREATE TABLE `delivery_services` (
  `id` INT (11) NOT NULL AUTO_INCREMENT,
  `unique_id` VARCHAR (100) NOT NULL,
  `user_id` INT (11) NOT NULL,
  `user_type` VARCHAR (20) NOT NULL DEFAULT 'provider',
  `service_title` VARCHAR (500) NOT NULL,
  `currency_code` VARCHAR (25),
  `service_sub_title` VARCHAR (500),
  `service_amount` FLOAT NOT NULL,
  `category` INT (11) NOT NULL,
  `about` TEXT NOT NULL,
  `service_offered` TEXT NOT NULL,
  `service_location` VARCHAR (500) NOT NULL,
  `service_latitude` VARCHAR (500) NOT NULL,
  `service_longitude` VARCHAR (500) NOT NULL,
  `service_image` TEXT NOT NULL,
  `service_details_image` TEXT NOT NULL,
  `thumb_image` TEXT NOT NULL,
  `mobile_image` TEXT NOT NULL,
  `status` INT (11) NOT NULL COMMENT '0-delete,1-active,2-inactive',
  `total_views` INT (11) NOT NULL,
  `rating` VARCHAR (255) NOT NULL,
  `rating_count` VARCHAR (255) NOT NULL,
  `admin_verification` INT (10),
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `dimention` VARCHAR (255) NOT NULL,
  PRIMARY KEY (`id`)
);