ALTER TABLE `book_service`   
  DROP COLUMN `from_time`, 
  DROP COLUMN `to_time`, 
  DROP COLUMN `category_id`, 
  DROP COLUMN `emp_id`, 
  DROP COLUMN `booking_status`, 
  DROP COLUMN `start_time`, 
  DROP COLUMN ` category_id`, 
  DROP COLUMN ` emp_id`, 
  DROP COLUMN ` booking_status`, 
  DROP COLUMN ` start_time`, 
  ADD COLUMN `service_time` TIME NOT NULL AFTER `service_date`,
  CHANGE `location` `location` VARCHAR(255) CHARSET latin1 COLLATE latin1_swedish_ci NOT NULL  AFTER `tokenid`,
  CHANGE `notes` `notes` TEXT CHARSET latin1 COLLATE latin1_swedish_ci NOT NULL  AFTER `longitude`,
  ADD COLUMN `first_name` VARCHAR(100) NOT NULL AFTER `updated_on`,
  ADD COLUMN `last_name` VARCHAR(100) NOT NULL AFTER `first_name`,
  ADD COLUMN `country` VARCHAR(50) NOT NULL AFTER `last_name`,
  ADD COLUMN `town` VARCHAR(100) NOT NULL AFTER `country`,
  ADD COLUMN `street_addr_1` VARCHAR(100) NOT NULL AFTER `town`,
  ADD COLUMN `street_addr_2` VARCHAR(100) NOT NULL AFTER `street_addr_1`,
  ADD COLUMN `phone` VARCHAR(100) NOT NULL AFTER `street_addr_2`,
  ADD COLUMN `email` VARCHAR(100) NOT NULL AFTER `phone`,
  CHARSET=utf8, COLLATE=utf8_general_ci;